image: 'xd009642/tarpaulin:latest'

build:
  stage: build

  script:
    # - cargo install cargo-tarpaulin
    - cargo tarpaulin --root Example-1/shapes/
    - cargo rustdoc --manifest-path=Example-1/shapes/Cargo.toml
    - cargo tarpaulin --root Example-2/shapes/
    - cargo rustdoc --manifest-path=Example-2/shapes/Cargo.toml
