image: 'xd009642/tarpaulin:latest'

build:
  stage: build

  script:
    # - cargo install cargo-tarpaulin
    - cargo tarpaulin --root Example-1/shapes/
    - cargo rustdoc --manifest-path=Example-1/shapes/Cargo.toml
    - cargo tarpaulin --root Example-2/shapes/
    - cargo rustdoc --manifest-path=Example-2/shapes/Cargo.toml
    - cargo tarpaulin --root Example-3/shapes/
    - cargo rustdoc --manifest-path=Example-3/shapes/Cargo.toml
    - cargo tarpaulin --root Example-4/shapes/
    - cargo rustdoc --manifest-path=Example-4/shapes/Cargo.toml
    - cargo tarpaulin --root Example-5/shapes/
    - cargo rustdoc --manifest-path=Example-5/shapes/Cargo.toml
    - cargo tarpaulin --root Example-6/shapes/
    - cargo rustdoc --manifest-path=Example-6/shapes/Cargo.toml
    - cargo tarpaulin --root Example-7/shapes/
    - cargo rustdoc --manifest-path=Example-7/shapes/Cargo.toml
