[package]
name = "shapes"
version = "0.1.0"
authors = ["Thomas J. Kennedy <tkennedy@cs.odu.edu>"]
edition = "2018"

[dependencies]
ordered-float = "1.0.2"

[dev-dependencies]
hamcrest2 = "*"
stringreader = "0.1.1"
